-- Up Migration
--
-- 0013: Analytics module (sibling to Forms / Reservations).
--
-- =============================================================================
-- IDEMPOTENCY STRATEGY
-- =============================================================================
-- Same shape as 0010 / 0011 — IF NOT EXISTS on every CREATE, plus a recovery
-- DO block at the top that drops the NEW tables on a partial-run state.
-- CREATE INDEX (no CONCURRENTLY) so the whole migration is atomic inside
-- node-pg-migrate's default transaction.
--
-- =============================================================================
-- MODULE SHAPE
-- =============================================================================
-- Two tables:
--
--   analytics_configs  — one row per project (FK projects.id, CASCADE, UNIQUE).
--                        Created lazily on first GET /api/analytics/by-project/:id
--                        or by an admin through the standard CRUD. Mirrors the
--                        forms.module's per-project model.
--                        Fields: project_id (UNIQUE FK), name, secret_token
--                        (22-char base64url UNIQUE capability), allowed_origins
--                        (text[]), status (active/disabled), timestamps.
--
--   analytics_events   — append-only event log. One row per emitted JS event
--                        (pageview / custom). Columns are pre-aggregated (path,
--                        referrer, locale, screen size) plus a `raw` JSONB blob
--                        for the full original payload. No UPDATE / DELETE on
--                        events; stats are computed at read time over a bounded
--                        window. Foreign key CASCADE on config so a deleted
--                        config wipes its events too.
--
-- Why a separate config table (and not a column on projects)? Same reason
-- forms has its own table: a project may have many analytics configs later
-- (e.g. multiple landing pages per project), and the secret_token + origin
-- allowlist + event log are tightly coupled. A column on projects would
-- lock the design to one config per project forever.
--
-- =============================================================================
-- WHY 1 ROW PER PROJECT (UNIQUE FK)
-- =============================================================================
-- For the MVP we want exactly ONE analytics config per project. The lazy
-- GET /api/analytics/by-project/:id endpoint creates the row on first call
-- so the operator doesn't have to navigate to /analytics/create. This
-- matches how the user described the workflow: "basic analytics for now,
-- a generated script snippet I can put into a landing page code".
--
-- Future: drop the UNIQUE and let one project have many configs (per-page
-- analytics). The lazy-create path and the secret_token uniqueness are
-- the only contracts the rest of the code depends on — no migrations
-- needed when we relax the cardinality.

-- ---------------------------------------------------------------------------
-- Recovery block: drop any partial-state from a previously-killed run.
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  DROP TABLE IF EXISTS analytics_events CASCADE;
  DROP TABLE IF EXISTS analytics_configs CASCADE;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE '0013: recovery drop of analytics tables skipped: %', SQLERRM;
END $$;

-- ---------------------------------------------------------------------------
-- Analytics configs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_configs (
  id              BIGSERIAL PRIMARY KEY,
  project_id      BIGINT NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
  -- Human-readable label, 1..200 chars.
  name            TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
  -- 22-char base64url = 16 random bytes, generated by the BE.
  -- Same entropy as forms.secret_token; used as the public-API capability.
  secret_token    TEXT NOT NULL UNIQUE CHECK (length(secret_token) = 22),
  -- Per-config host-allowlist (text[]). Empty = no restriction (open).
  -- Mirrors forms.allowed_origins semantics exactly.
  allowed_origins TEXT[] NOT NULL DEFAULT '{}',
  -- TEXT + CHECK, not PG ENUM (per the orchestrator decision on forms).
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Per-table trigger function for updated_at (mirrors projects / forms / reservations).
CREATE OR REPLACE FUNCTION analytics_configs_touch_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_analytics_configs_touch_updated_at ON analytics_configs;
CREATE TRIGGER trg_analytics_configs_touch_updated_at
  BEFORE UPDATE ON analytics_configs
  FOR EACH ROW EXECUTE FUNCTION analytics_configs_touch_updated_at();

-- Partial index for active configs (the public embed only serves active ones).
CREATE INDEX IF NOT EXISTS idx_analytics_configs_status
  ON analytics_configs(status) WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- Analytics events (append-only log)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analytics_events (
  id             BIGSERIAL PRIMARY KEY,
  config_id      BIGINT NOT NULL REFERENCES analytics_configs(id) ON DELETE CASCADE,
  -- Whitelisted event types. Keep this list tight — it's both an API guard
  -- and a query-side filter (`event_type = 'pageview'` for the dashboard).
  event_type     TEXT NOT NULL CHECK (event_type IN ('pageview', 'event')),
  occurred_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Session id: stable per browser tab/visit, generated by the JS loader
  -- (crypto.randomUUID() when available, else a fallback). 64 chars max.
  session_id     TEXT,
  -- Long-lived visitor id, persisted in localStorage by the JS loader.
  visitor_id     TEXT,
  -- Path: relative URL path of the page (the host is already known server-side
  -- via req.headers.host). Trimmed server-side to 2000 chars; no scheme/host.
  path           TEXT,
  -- Referrer: full URL trimmed to 2000 chars on insert.
  referrer       TEXT,
  screen_width   INT,
  screen_height  INT,
  locale         TEXT,
  -- User agent truncated to 500 chars by the BE (we don't trust the header).
  user_agent     TEXT,
  -- INET captures both v4 and v6; pg returns strings.
  ip_address     INET,
  -- Bounded-bag JSONB blob with the full original event payload (extra
  -- metadata that doesn't have its own column).
  raw            JSONB
);

-- Stats queries are scoped per-config and filtered by occurred_at (e.g.
-- "events in the last 30 days for config N, grouped by path"). The composite
-- (config_id, occurred_at DESC) index covers that and the newest-first
-- listing path.
CREATE INDEX IF NOT EXISTS idx_analytics_events_config_occurred
  ON analytics_events (config_id, occurred_at DESC);
-- Secondary index on (config_id, event_type, occurred_at DESC) for the
-- per-type breakdown in the stats endpoint.
CREATE INDEX IF NOT EXISTS idx_analytics_events_config_type_occurred
  ON analytics_events (config_id, event_type, occurred_at DESC);

-- Down Migration

DROP TRIGGER IF EXISTS trg_analytics_configs_touch_updated_at ON analytics_configs;
DROP FUNCTION IF EXISTS analytics_configs_touch_updated_at();
DROP TABLE IF EXISTS analytics_events;
DROP TABLE IF EXISTS analytics_configs;
